# GitHub Actions 测试用
# 移动端配置

client:
  impl: api
  domain: [
    "www.jmapinode1.cc",
    "www.jmapinode2.cc",
    "www.jmapinode3.cc",
    "www.jmapibranch2.cc"
  ]
  postman:
    meta_data:
      timeout: 10

# 插件配置
plugin:
  after_init:
    - plugin: usage_log # 实时打印硬件占用率的插件
      kwargs:
        interval: 0.5 # 间隔时间
        enable_warning: false # 不告警
